In [1]:
# for "2. Data Loading"
import pandas as pd

# for "3-1. Feature Generation"
import numpy as np

# for "3-2. Feature Engineering"
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import RobustScaler, StandardScaler

# for "4. Modeling with Pycaret"
from pycaret.regression import *

# for "5. Modeling with CatBoostRegressor"
from catboost import CatBoostRegressor
import optuna
from optuna import Trial
from optuna.samplers import TPESampler
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split, StratifiedKFold

In [2]:
# 데이터 로드
pre_tr = pd.read_csv('data_preprocess/pre_tr_1118.csv',encoding = "cp949")
pre_te = pd.read_csv('data_preprocess/pre_te_1118.csv',encoding = "cp949")
pre_tr = pre_tr.set_index("일자")
pre_te = pre_te.set_index("일자")
today = "1118_1"

In [3]:
# 데이터 확인
pre_tr.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1205 entries, 2016-02-01 to 2021-01-26
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   요일      1205 non-null   int64
 1   정원수     1205 non-null   int64
 2   휴가자수    1205 non-null   int64
 3   출장자수    1205 non-null   int64
 4   야근자수    1205 non-null   int64
 5   재택근무자수  1205 non-null   float64
 6   조식메뉴    1205 non-null   object
 7   중식메뉴    1205 non-null   object
 8   석식메뉴    1205 non-null   object
 9   중식계     1205 non-null   float64
 10  석식계     1205 non-null   float64
 11  출근자수    1205 non-null   float64
 12  월       1205 non-null   int64
 13  년도      1205 non-null   int64
dtypes: float64(4), int64(7), object(3)
memory usage: 141.2+ KB

조식메뉴, 중식메뉴, 석식메뉴 다 없어도 될거 같은데,,,?
일자도 일단 제외하고 진행

In [4]:
# #학습용 데이터셋 생성
# train = pre_tr.loc[:,"요일":"재택근무자수"]
# train["출근자수"] = pre_tr["출근자수"]
# display(train)
# test = pre_te.loc[:,"요일":"재택근무자수"]
# test["출근자수"] = pre_te["출근자수"]
# display(test)

In [5]:
#학습용 데이터셋 생성
train_dr = pre_tr.loc[:,"조식메뉴":"석식계"]
train = pre_tr.drop(train_dr,axis=1)
display(train)
test_dr = pre_te.loc[:,"조식메뉴":"석식메뉴"]
test = pre_te.drop(test_dr,axis=1)
display(test)

            요일   정원수  휴가자수  출장자수  야근자수  재택근무자수    출근자수  월    년도
일자
2016-02-01   1  2601    50   150   238     0.0  2401.0  2  2016
2016-02-02   2  2601    50   173   319     0.0  2378.0  2  2016
2016-02-03   3  2601    56   180   111     0.0  2365.0  2  2016
2016-02-04   4  2601   104   220   355     0.0  2277.0  2  2016
2016-02-05   5  2601   278   181    34     0.0  2142.0  2  2016
...         ..   ...   ...   ...   ...     ...     ... ..   ...
2021-01-20   3  2983    75   198     4   391.0  2319.0  1  2021
2021-01-21   4  2983    92   231   462   351.0  2309.0  1  2021
2021-01-22   5  2983   255   248     1   303.0  2177.0  1  2021
2021-01-25   1  2983   107   153   616   327.0  2396.0  1  2021
2021-01-26   2  2983    69   183   551   362.0  2369.0  1  2021

[1205 rows x 9 columns]

            요일   정원수  휴가자수  출장자수  야근자수  재택근무자수    출근자수  월    년도
일자
2021-01-27   3  2983    88   182     5   358.0  2401.0  1  2021
2021-01-28   4  2983   104   212   409   348.0  2378.0  1  2021
2021-01-29   5  2983   270   249     0   294.0  2365.0  1  2021
2021-02-01   1  2924   108   154   538   322.0  2277.0  2  2021
2021-02-02   2  2924    62   186   455   314.0  2142.0  2  2021
2021-02-03   3  2924    59   199     5   286.0  2075.0  2  2021
2021-02-04   4  2924    61   211   476   288.0  2056.0  2  2021
2021-02-05   5  2924   169   252     0   256.0  2310.0  2  2021
2021-02-08   1  2924    88   174   690   329.0  2293.0  2  2021
2021-02-09   2  2924    94   183   542   329.0  2273.0  2  2021
2021-02-10   3  2924   489   134     0   233.0  2270.0  2  2021
2021-02-15   1  2924   178   131   795   355.0  2204.0  2  2021
2021-02-16   2  2924    70   175   815   413.0  2304.0  2  2021
2021-02-17   3  2924    77   181     3   379.0  2307.0  2  2021
2021-02-18   4  2924    83   247   594   338.0  2315.0  2  2021
2021-02-19   5  2924   176   268     1   280.0  2284.0  2  2021
2021-02-22   1  2924   105   197   814   247.0  2179.0  2  2021
2021-02-23   2  2924    75   200   783   233.0  1838.0  2  2021
2021-02-24   3  2924    77   235     3   234.0  2315.0  2  2021
2021-02-25   4  2924    91   252   585   235.0  2339.0  2  2021
2021-02-26   5  2924   261   279     1   179.0  2294.0  2  2021
2021-03-02   2  2975   139   166   781   248.0  2379.0  3  2021
2021-03-03   3  2975    50   195     1   292.0  2365.0  3  2021
2021-03-04   4  2975    72   236   746   263.0  2356.0  3  2021
2021-03-05   5  2975   158   257     2   226.0  2324.0  3  2021
2021-03-08   1  2975    97   170   939   264.0  2241.0  3  2021
2021-03-09   2  2975    76   170  1003   282.0  2380.0  3  2021
2021-03-10   3  2975    71   185     1   271.0  2355.0  3  2021
2021-03-11   4  2975    93   223   609   261.0  2361.0  3  2021
2021-03-12   5  2975   241   240     0   251.0  2330.0  3  2021
2021-03-15   1  2975   126   148   864   314.0  2229.0  3  2021
2021-03-16   2  2975    74   176   658   401.0  2354.0  3  2021
2021-03-17   3  2975    90   192     4   371.0  2375.0  3  2021
2021-03-18   4  2975   106   231   520   351.0  2346.0  3  2021
2021-03-19   5  2975   253   255     0   266.0  2320.0  3  2021
2021-03-22   1  2975   133   166   707   350.0  2251.0  3  2021
2021-03-23   2  2975    82   205   688   349.0  2350.0  3  2021
2021-03-24   3  2975    87   234     0   314.0  2327.0  3  2021
2021-03-25   4  2975   118   260   441   297.0  2346.0  3  2021
2021-03-26   5  2975   311   266     0   229.0  2340.0  3  2021
2021-03-29   1  2975   121   178   660   318.0  2286.0  3  2021
2021-03-30   2  2975    83   198   625   313.0  2360.0  3  2021
2021-03-31   3  2975    86   217     0   317.0  2370.0  3  2021
2021-04-01   4  2973    88   256   394   303.0  2357.0  4  2021
2021-04-02   5  2973   275   272     0   224.0  2338.0  4  2021
2021-04-05   1  2973   125   174   704   331.0  2273.0  4  2021
2021-04-06   2  2973    76   170   636   364.0  2358.0  4  2021
2021-04-07   3  2973    96   214     1   334.0  2342.0  4  2021
2021-04-08   4  2973   105   238   509   324.0  2285.0  4  2021
2021-04-09   5  2973   259   268     0   229.0  2231.0  4  2021

In [6]:
#중식 타겟 데이터
y_lun = pre_tr["중식계"]
# 석식 타겟 데이터
y_din = pre_tr["석식계"]

## 중식계 예측

In [7]:
def objective(trial: Trial) -> float:
    params_cat = {
        "random_state": 42,
        "learning_rate": 0.05,
        "n_estimators": 10000,
        "verbose" : 1,
        "objective" : "MAE",
        "max_depth": trial.suggest_int("max_depth", 1, 16),
        "colsample_bylevel": trial.suggest_float("colsample_bylevel", 0.8, 1.0),
        "subsample": trial.suggest_float("subsample", 0.3, 1.0),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
        "max_bin": trial.suggest_int("max_bin", 200, 500),
    }
    
    X_tr, X_val, y_tr, y_val = train_test_split(train, y_lun, test_size=0.2)

    model = CatBoostRegressor(**params_cat)
    model.fit(
        X_tr,
        y_tr,
        eval_set=[(X_tr, y_tr), (X_val, y_val)],
        early_stopping_rounds=10,
        verbose=False,
    )

    cat_pred = model.predict(X_val)
    log_score = mean_absolute_error(y_val, cat_pred)
    
    return log_score

In [8]:
sampler = TPESampler(seed=42)
study = optuna.create_study(
    study_name="cat_opt",
    direction="minimize",
    sampler=sampler,
)
study.optimize(objective, n_trials=10)
print("Best Score:", study.best_value)
print("Best trial:", study.best_trial.params)

[I 2021-11-18 15:39:53,639] A new study created in memory with name: cat_opt
[I 2021-11-18 15:39:54,079] Trial 0 finished with value: 63.79821182915783 and parameters: {'max_depth': 6, 'colsample_bylevel': 0.9901428612819833, 'subsample': 0.8123957592679836, 'min_child_samples': 62, 'max_bin': 246}. Best is trial 0 with value: 63.79821182915783.
[I 2021-11-18 15:39:54,284] Trial 1 finished with value: 68.97907610018224 and parameters: {'max_depth': 3, 'colsample_bylevel': 0.8116167224336399, 'subsample': 0.9063233020424546, 'min_child_samples': 62, 'max_bin': 413}. Best is trial 0 with value: 63.79821182915783.
[I 2021-11-18 15:39:54,544] Trial 2 finished with value: 82.77094711625148 and parameters: {'max_depth': 1, 'colsample_bylevel': 0.9939819704323989, 'subsample': 0.8827098485602951, 'min_child_samples': 25, 'max_bin': 254}. Best is trial 0 with value: 63.79821182915783.
[I 2021-11-18 15:39:54,841] Trial 3 finished with value: 71.08322162771738 and parameters: {'max_depth': 3, 'colsample_bylevel': 0.8608484485919076, 'subsample': 0.6673295021425665, 'min_child_samples': 46, 'max_bin': 287}. Best is trial 0 with value: 63.79821182915783.
[I 2021-11-18 15:39:57,355] Trial 4 finished with value: 72.54031156984831 and parameters: {'max_depth': 10, 'colsample_bylevel': 0.8278987721304084, 'subsample': 0.5045012539746527, 'min_child_samples': 40, 'max_bin': 337}. Best is trial 0 with value: 63.79821182915783.
[I 2021-11-18 15:40:14,068] Trial 5 finished with value: 65.65126430581448 and parameters: {'max_depth': 13, 'colsample_bylevel': 0.8399347564316719, 'subsample': 0.6599641068895281, 'min_child_samples': 61, 'max_bin': 213}. Best is trial 0 with value: 63.79821182915783.
[I 2021-11-18 15:40:18,424] Trial 6 finished with value: 66.97477508100214 and parameters: {'max_depth': 10, 'colsample_bylevel': 0.8341048247374584, 'subsample': 0.3455361150896956, 'min_child_samples': 96, 'max_bin': 490}. Best is trial 0 with value: 63.79821182915783.
[I 2021-11-18 15:40:39,990] Trial 7 finished with value: 73.11813479327367 and parameters: {'max_depth': 13, 'colsample_bylevel': 0.8609227538346742, 'subsample': 0.3683704798044687, 'min_child_samples': 70, 'max_bin': 332}. Best is trial 0 with value: 63.79821182915783.
[I 2021-11-18 15:40:40,506] Trial 8 finished with value: 65.09429696405607 and parameters: {'max_depth': 2, 'colsample_bylevel': 0.8990353820222541, 'subsample': 0.32407196478065287, 'min_child_samples': 92, 'max_bin': 277}. Best is trial 0 with value: 63.79821182915783.
[I 2021-11-18 15:40:44,902] Trial 9 finished with value: 71.94553095503731 and parameters: {'max_depth': 11, 'colsample_bylevel': 0.8623422152178822, 'subsample': 0.6640476148244676, 'min_child_samples': 57, 'max_bin': 255}. Best is trial 0 with value: 63.79821182915783.

Best Score: 63.79821182915783
Best trial: {'max_depth': 6, 'colsample_bylevel': 0.9901428612819833, 'subsample': 0.8123957592679836, 'min_child_samples': 62, 'max_bin': 246}

In [9]:
cat_p = study.best_trial.params
cat = CatBoostRegressor(**cat_p)

In [10]:
y_cat = pd.cut(y_lun, 10, labels=range(10))
skf = StratifiedKFold(5)

preds = []
for tr_id, val_id in skf.split(train, y_cat) : 
    X_tr = train.iloc[tr_id]
    y_tr = y_lun.iloc[tr_id]
    
    cat.fit(X_tr, y_tr, verbose = 0)
    
    pred = cat.predict(test)
    preds.append(pred)
cat_pred = np.mean(preds, axis = 0)

In [11]:
sample = pd.read_csv('sub/sample_submission.csv', encoding = "cp949")
sample['중식계'] = cat_pred

## 석식계 예측

In [12]:
def objective(trial: Trial) -> float:
    params_cat = {
        "random_state": 42,
        "learning_rate": 0.05,
        "n_estimators": 10000,
        "verbose" : 1,
        "objective" : "MAE",
        "max_depth": trial.suggest_int("max_depth", 1, 16),
        "colsample_bylevel": trial.suggest_float("colsample_bylevel", 0.8, 1.0),
        "subsample": trial.suggest_float("subsample", 0.3, 1.0),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
        "max_bin": trial.suggest_int("max_bin", 200, 500),
    }
    
    X_tr, X_val, y_tr, y_val = train_test_split(train, y_din, test_size=0.2)

    model = CatBoostRegressor(**params_cat)
    model.fit(
        X_tr,
        y_tr,
        eval_set=[(X_tr, y_tr), (X_val, y_val)],
        early_stopping_rounds=10,
        verbose=False,
    )

    cat_pred = model.predict(X_val)
    log_score = mean_absolute_error(y_val, cat_pred)
    
    return log_score

In [13]:
sampler = TPESampler(seed=42)
study = optuna.create_study(
    study_name="cat_opt",
    direction="minimize",
    sampler=sampler,
)
study.optimize(objective, n_trials=10)
print("Best Score:", study.best_value)
print("Best trial:", study.best_trial.params)

[I 2021-11-18 15:40:58,010] A new study created in memory with name: cat_opt
[I 2021-11-18 15:40:58,667] Trial 0 finished with value: 53.17292331624348 and parameters: {'max_depth': 6, 'colsample_bylevel': 0.9901428612819833, 'subsample': 0.8123957592679836, 'min_child_samples': 62, 'max_bin': 246}. Best is trial 0 with value: 53.17292331624348.
[I 2021-11-18 15:40:59,275] Trial 1 finished with value: 64.72923684762425 and parameters: {'max_depth': 3, 'colsample_bylevel': 0.8116167224336399, 'subsample': 0.9063233020424546, 'min_child_samples': 62, 'max_bin': 413}. Best is trial 0 with value: 53.17292331624348.
[I 2021-11-18 15:40:59,844] Trial 2 finished with value: 60.14952298847449 and parameters: {'max_depth': 1, 'colsample_bylevel': 0.9939819704323989, 'subsample': 0.8827098485602951, 'min_child_samples': 25, 'max_bin': 254}. Best is trial 0 with value: 53.17292331624348.
[I 2021-11-18 15:41:00,392] Trial 3 finished with value: 56.080003132529455 and parameters: {'max_depth': 3, 'colsample_bylevel': 0.8608484485919076, 'subsample': 0.6673295021425665, 'min_child_samples': 46, 'max_bin': 287}. Best is trial 0 with value: 53.17292331624348.
[I 2021-11-18 15:41:02,807] Trial 4 finished with value: 56.29847964752225 and parameters: {'max_depth': 10, 'colsample_bylevel': 0.8278987721304084, 'subsample': 0.5045012539746527, 'min_child_samples': 40, 'max_bin': 337}. Best is trial 0 with value: 53.17292331624348.
[I 2021-11-18 15:41:15,292] Trial 5 finished with value: 66.92798327074422 and parameters: {'max_depth': 13, 'colsample_bylevel': 0.8399347564316719, 'subsample': 0.6599641068895281, 'min_child_samples': 61, 'max_bin': 213}. Best is trial 0 with value: 53.17292331624348.
[I 2021-11-18 15:41:18,907] Trial 6 finished with value: 69.29123533329893 and parameters: {'max_depth': 10, 'colsample_bylevel': 0.8341048247374584, 'subsample': 0.3455361150896956, 'min_child_samples': 96, 'max_bin': 490}. Best is trial 0 with value: 53.17292331624348.
[I 2021-11-18 15:41:34,944] Trial 7 finished with value: 65.95215556803801 and parameters: {'max_depth': 13, 'colsample_bylevel': 0.8609227538346742, 'subsample': 0.3683704798044687, 'min_child_samples': 70, 'max_bin': 332}. Best is trial 0 with value: 53.17292331624348.
[I 2021-11-18 15:41:35,536] Trial 8 finished with value: 63.87868775035199 and parameters: {'max_depth': 2, 'colsample_bylevel': 0.8990353820222541, 'subsample': 0.32407196478065287, 'min_child_samples': 92, 'max_bin': 277}. Best is trial 0 with value: 53.17292331624348.
[I 2021-11-18 15:41:39,675] Trial 9 finished with value: 64.02860253948572 and parameters: {'max_depth': 11, 'colsample_bylevel': 0.8623422152178822, 'subsample': 0.6640476148244676, 'min_child_samples': 57, 'max_bin': 255}. Best is trial 0 with value: 53.17292331624348.

Best Score: 53.17292331624348
Best trial: {'max_depth': 6, 'colsample_bylevel': 0.9901428612819833, 'subsample': 0.8123957592679836, 'min_child_samples': 62, 'max_bin': 246}

In [14]:
cat_p2 = study.best_trial.params
cat2 = CatBoostRegressor(**cat_p2)

In [15]:
y_cat2 = pd.cut(y_din, 10, labels=range(10))
skf2 = StratifiedKFold(5)

preds = []
for tr_id, val_id in skf2.split(train, y_cat2) : 
    X_tr2 = train.iloc[tr_id]
    y_tr2 = y_din.iloc[tr_id]
    
    cat2.fit(X_tr2, y_tr2, verbose = 0)
    
    pred = cat2.predict(test)
    preds.append(pred)
cat_pred_din = np.mean(preds, axis = 0)

In [16]:
sample['석식계'] = cat_pred_din

In [17]:
sample

            일자          중식계         석식계
0   2021-01-27  1001.826743  352.185498
1   2021-01-28   911.261017  384.924076
2   2021-01-29   625.467143  283.943238
3   2021-02-01  1171.085692  535.647314
4   2021-02-02   957.754790  447.835325
5   2021-02-03   922.254382  385.277740
6   2021-02-04   874.490203  434.038942
7   2021-02-05   643.441877  337.263953
8   2021-02-08  1184.440637  596.137771
9   2021-02-09  1006.342829  505.326021
10  2021-02-10   819.995743  269.913775
11  2021-02-15  1180.918876  681.936868
12  2021-02-16  1033.212221  601.417994
13  2021-02-17  1035.699174  392.010193
14  2021-02-18   864.706398  488.604575
15  2021-02-19   622.210272  355.480580
16  2021-02-22  1155.721349  618.262563
17  2021-02-23   976.492145  557.396429
18  2021-02-24   857.833873  349.276264
19  2021-02-25   845.644808  471.264925
20  2021-02-26   581.264697  307.241312
21  2021-03-02  1057.977738  658.789705
22  2021-03-03   968.670578  408.003288
23  2021-03-04   917.550996  519.629929
24  2021-03-05   634.883688  355.970966
25  2021-03-08  1210.240628  666.157331
26  2021-03-09  1080.470202  666.286360
27  2021-03-10  1021.150035  425.638103
28  2021-03-11   912.570477  507.133023
29  2021-03-12   654.848105  310.541188
30  2021-03-15  1191.673171  667.832238
31  2021-03-16   997.976939  552.858078
32  2021-03-17  1035.890837  390.296081
33  2021-03-18   886.212644  452.390908
34  2021-03-19   627.906603  292.740838
35  2021-03-22  1182.365785  620.727158
36  2021-03-23   990.220709  563.384843
37  2021-03-24   880.889356  339.790862
38  2021-03-25   850.452771  427.166935
39  2021-03-26   592.277199  295.290665
40  2021-03-29  1181.943315  601.512383
41  2021-03-30  1005.793424  545.310531
42  2021-03-31   927.023805  394.201817
43  2021-04-01   803.376744  408.239231
44  2021-04-02   591.055669  292.020857
45  2021-04-05  1150.691267  589.122702
46  2021-04-06   994.107946  554.058105
47  2021-04-07   966.423376  390.667835
48  2021-04-08   851.237432  436.440574
49  2021-04-09   578.233474  301.920506

In [18]:
sample.to_csv('sub/Model_Cat_{}.csv'.format(today), index=False)